# Redcarpet is a Markdown processor
# It's the thing that converts Markdown to HTML
# Github uses Redcarpet for conversion so we want to remain consistent
markdown: redcarpet
# The folder our website is hosted in
# Everything that comes after http://emmyB92.github.io
baseurl : /dinosaurs